---
# defaults file for part24-jenkins-jcasc
jenkins_user: "mamad"
jenkins_password: "123456"
jenkins_url: "http://<jenkins-server>:<jenkins-port>"
jk_plugins:
  configuration-as-code:
    enabled: True
  structs:
    enabled: True
  folders:
    enabled: True
  script-security:
    enabled: True
  branch-api:
    enabled: True
  matrix-auth:
    enabled: True
  job-dsl:
    enabled: True
  generic-webhook-trigger:
    enabled: True
    # version: 1.79
    # pinned: true