- name: Stop Jenkins service
  systemd:
    name: jenkins
    state: stopped
    enabled: no 

- name: Remove a file
  file:
    path: /var/lib/jenkins/secrets/initialAdminPassword
    state: absent

- name: Create a folder
  file:
    path: /var/lib/jenkins/casc_configs/
    state: directory
    owner: jenkins
    group: jenkins
    mode: '0755'  

- name: Copy JCasC system config
  copy:
    src: casc.yaml
    dest: /var/lib/jenkins/casc_configs/casc.yaml
    owner: jenkins
    group: jenkins
    mode: '0644'

- name: Replace jenkins system config 
  copy:
    src: jenkins.service
    dest: /usr/lib/systemd/system/jenkins.service
    owner: jenkins
    group: jenkins
    mode: '0644'
    backup: yes

- name: Reload systemd after replacing service
  command: systemctl daemon-reload
  become: yes
  
- name: Restart Jenkins
  systemd:
    name: jenkins
    state: restarted
