- name: Check if Jenkins initialAdminPassword file exists
  stat:
    path: /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkins_pass_file

- name: Get jenkins admin Password
  command: "cat  /var/lib/jenkins/secrets/initialAdminPassword"
  register:  out
  when: jenkins_pass_file.stat.exists
  ignore_errors: yes

- name: Set Jenkins password variable
  set_fact:
    jenkins_password1: "{{ out.stdout if jenkins_pass_file.stat.exists else '{{jenkins_password'}} }}"

- name: debug
  debug:
    msg: "password: {{jenkins_password1}}"